import numpy as np
#arr = np.array((1, 2, 3, 6, 3))
#arr = np.array(42)
#arr = np.array([[[1, 2, 3], [4, 5,bayes 6]], [[1, 2, 3], [4, 5, 6]]])
#a = np.array(42)
#b = np.array([1, 2, 3, 4, 5])
#c = np.array([[1, 2, 3], [4, 5, 6]])
#d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
#print(a.ndim)
#print(b.ndim)
#print(c.ndim)
#print(d.ndim)
#print(arr)
#print (type(arr))
#print(np.__version__)
#arr = np.array([1, 2, 3, 4], ndmin=5)
#print(arr)
#print('number of dimensions is ',arr.ndim)

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[0])